#IMPUT SOLICITANDO A BEBIDA
#UMA FUNÇAO PARA VERIFICAR SE TEM RECURSOS PARA FAZER A BEBIDA
#UMA FUNCAO PARA RECOLHER O DINHEIRO E CONFERIR
#UMA FUNCAO PARA COMPARAR O VALOR INSERIDO COM O VALOR DA BEBIDA
#UMA 
